import React from 'react'
import { render } from 'react-dom'
import {
  SmartphoneOutlined,
  PlaneFilled,
  GiftOutlined,
  SmartphoneColored,
  AndroidColored,
  BehanceColored,
  BoxLogoColored,
  DribbbleColored,
  DropboxColored,
  EtsyColored,
  FacebookColored,
  GoogleColored,
  PlaneColored,
  RoomKeyColored,
  FlickrColored,
  GooglePlusColored,
  InstagramColored,
  KickstarterColored,
  LinkedinColored,
  MediumColored,
  PaypalColored,
  PeriscopeColored,
  PinterestColored,
  RedditColored,
  FlowerColored,
  GiftFilled,
  GiftColored,
  MusicPlayerColored,
  MusicPlayerFilled,
  MusicPlayerOutlined,
  WeightColored,
  WeightFilled,
  WeightOutlined,
  ScribdColored,
  SkypeColored,
  SnapchatColored,
  SoundCloudColored,
  SpotifyColored,
  TrelloColored,
  TumblrColored,
  TwitterColored,
  VimeoColored,
  VineColored,
  WhatsAppColored,
  WhatsAppOutlined,
  WikipediaColored,
  WordpressColored,
  YelpColored,
  YouTubeColored,
  SocialMediaOutlined,
  RoomKeyFilled,
  RoomKeyOutlined,
  HeartFilled,
  HeartColored,
  ComputerScreenColored,
  ComputerScreenOutlined,
  ComputerScreenFilled,
  MapOutlined,
  MapFilled,
  MapColored,
  NavigationFilled,
  NavigationOutlined,
  NavigationColored,
  AwardFilled,
  AwardOutlined,
  AwardColored,
  TvFilled,
  TvOutlined,
  TvColored,
  TaxiColored,
  TaxiFilled,
  TaxiOutlined,
  ConfigurationColored,
  ConfigurationFilled,
  ConfigurationOutlined,
  ParkTreeColored,
  ParkTreeOutlined,
  ParkTreeFilled,
  TrashColored,
  TrashOutlined,
  TrashFilled,
  ChatColored,
  ChatFilled,
  ChatOutlined,
  PencilColored,
  PencilFilled,
  PencilOutlined,
  CameraColored,
  CameraFilled,
  CameraOutlined,
  GraduationCapColored,
  GraduationCapOutlined,
  GraduationCapFilled,
  ColorPaletteColored,
  ColorPaletteFilled,
  ColorPaletteOutlined,
} from '../../lib'

import './styles.css'
// <GraduationCapFilled color="blue"/>
const App = () => (
  <div>
    <h1>Icon Demos</h1>
    <ColorPaletteOutlined/>
    <ColorPaletteFilled/>
    <ColorPaletteColored/>
    <GraduationCapFilled/>
    <GraduationCapOutlined/>
    <GraduationCapColored/>
    <CameraOutlined/>
    <CameraFilled/>
    <CameraColored/>
    <PencilOutlined/>
    <PencilFilled/>
    <PencilColored/>
    <ChatOutlined/>
    <ChatFilled/>
    <ChatColored/>
    <TrashFilled/>
    <TrashOutlined/>
    <TrashColored/>
    <ParkTreeFilled/>
    <ParkTreeOutlined/>
    <ConfigurationOutlined/>
    <ConfigurationFilled/>
    <ConfigurationColored/>
    <ParkTreeColored/>
    <TaxiOutlined/>
    <TaxiFilled/>
    <TaxiColored/>
    <TvColored/>
    <TvOutlined/>
    <TvFilled/>
    <AwardColored/>
    <AwardOutlined/>
    <AwardFilled/>
    <NavigationColored/>
    <NavigationOutlined/>
    <NavigationFilled/>
    <MapColored/>
    <MapFilled/>
    <MapOutlined/>
    <ComputerScreenFilled/>
    <ComputerScreenOutlined/>
    <ComputerScreenColored/>
    <HeartColored/>
    <HeartFilled/>
    <RoomKeyOutlined/>
    <RoomKeyFilled/>
    <SocialMediaOutlined/>
    <InstagramColored/>
    <YouTubeColored/>
    <YelpColored/>
    <WordpressColored/>
    <WikipediaColored/>
    <WhatsAppOutlined/>
    <WhatsAppColored/>
    <VineColored/>
    <VimeoColored/>
    <TwitterColored/>
    <TumblrColored/>
    <TrelloColored/>
    <SpotifyColored/>
    <SoundCloudColored/>
    <SnapchatColored/>
    <SkypeColored/>
    <ScribdColored/>
    <WeightOutlined/>
    <WeightFilled/>
    <WeightColored/>
    <MusicPlayerColored/>
    <MusicPlayerOutlined/>
    <MusicPlayerFilled/>
    <GiftColored/>
    <SmartphoneOutlined/>
    <PlaneFilled/>
    <GiftOutlined/>
    <SmartphoneColored/>
    <AndroidColored/>
    <BehanceColored/>
    <BoxLogoColored/>
    <DribbbleColored/>
    <DropboxColored/>
    <EtsyColored/>
    <FacebookColored/>
    <GoogleColored/>
    <PlaneColored/>
    <RoomKeyColored/>
    <FlickrColored/>
    <GooglePlusColored/>
    <KickstarterColored/>
    <LinkedinColored/>
    <MediumColored/>
    <PaypalColored/>
    <PeriscopeColored/>
    <PinterestColored/>
    <RedditColored/>
    <FlowerColored/>
    <GiftFilled/>
  </div>
)

render(<App />, document.getElementById("root"))
